"""flash sale model update

Revision ID: e1b61009c534
Revises: 
Create Date: 2025-12-05 13:25:42.023696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b61009c534'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_table('price_history')
    op.add_column('flash_sale_orders', sa.Column('client_ip', sa.String(), nullable=True))
    op.add_column('flash_sale_orders', sa.Column('device_fingerprint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flash_sale_orders', 'device_fingerprint')
    op.drop_column('flash_sale_orders', 'client_ip')
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(), nullable=True),
    sa.Column('price_type', sa.VARCHAR(), nullable=True),
    sa.Column('old_price', sa.FLOAT(), nullable=True),
    sa.Column('new_price', sa.FLOAT(), nullable=True),
    sa.Column('changed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###
